### PR TITLE
Fixing rust example (fixes #22556)

### LINKED ISSUE #22556: The Rust demo is broken
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

The Rust demo sitting here: https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-Rust, is currently broken:

```
andre@5090:/media/4tbdrive/engines/ultralytics/examples/YOLOv8-ONNXRuntime-Rust$ cargo build
    Updating crates.io index
     Locking 301 packages to latest compatible versions
      Adding dirs v5.0.1 (available: v6.0.0)
      Adding rand v0.8.5 (available: v0.9.2)
      Adding smallvec v2.0.0-alpha.10 (available: v2.0.0-alpha.11)
      Adding ureq v2.12.1 (available: v3.1.2)
  Downloaded ab_glyph v0.2.32
  Downloaded ab_glyph_rasterizer v0.1.10
  Downloaded clap v4.5.51
  Downloaded clap_lex v0.7.6
  Downloaded base64ct v1.8.0
  Downloaded approx v0.5.1
  Downloaded anstyle-query v1.1.4
  Downloaded anstyle v1.0.13
  Downloaded dirs v5.0.1
  Downloaded clap_derive v4.5.49
  Downloaded anstream v0.6.21
  Downloaded owned_ttf_parser v0.25.1
  Downloaded cc v1.2.44
  Downloaded potential_utf v0.1.4
  Downloaded der v0.7.10
  Downloaded pem-rfc7468 v0.7.0
  Downloaded writeable v0.6.2
  Downloaded clap_builder v4.5.51
  Downloaded yoke-derive v0.8.1
  Downloaded zerovec-derive v0.11.2
  Downloaded iana-time-zone v0.1.64
  Downloaded simba v0.8.1
  Downloaded rusttype v0.9.3
  Downloaded is_terminal_polyfill v1.70.2
  Downloaded tinystr v0.8.2
  Downloaded icu_provider v2.1.1
  Downloaded yoke v0.8.1
  Downloaded unicode-ident v1.0.22
  Downloaded icu_properties v2.1.1
  Downloaded litemap v0.8.1
  Downloaded icu_locale_core v2.1.1
  Downloaded zerotrie v0.2.3
  Downloaded safe_arch v0.7.4
  Downloaded icu_collections v2.1.1
  Downloaded openssl-sys v0.9.110
  Downloaded zerovec v0.11.5
  Downloaded wide v0.7.33
  Downloaded owned_ttf_parser v0.15.2
  Downloaded imageproc v0.25.0
  Downloaded icu_properties_data v2.1.1
  Downloaded webpki-root-certs v1.0.3
  Downloaded chrono v0.4.42
  Downloaded ttf-parser v0.25.1
  Downloaded ttf-parser v0.15.2
  Downloaded icu_normalizer_data v2.1.1
  Downloaded icu_normalizer v2.1.1
  Downloaded openssl v0.10.74
  Downloaded nalgebra v0.32.6
  Downloaded 48 crates (3.5MiB) in 0.35s
   Compiling proc-macro2 v1.0.103
   Compiling quote v1.0.41
   Compiling unicode-ident v1.0.22
   Compiling cfg-if v1.0.4
   Compiling libc v0.2.177
   Compiling autocfg v1.5.0
   Compiling libm v0.2.15
   Compiling find-msvc-tools v0.1.4
   Compiling shlex v1.3.0
   Compiling once_cell v1.21.3
   Compiling zeroize v1.8.2
   Compiling stable_deref_trait v1.2.1
   Compiling log v0.4.28
   Compiling adler2 v2.0.1
   Compiling typenum v1.19.0
   Compiling crc32fast v1.5.0
   Compiling vcpkg v0.2.15
   Compiling crossbeam-utils v0.8.21
   Compiling zerocopy v0.8.27
   Compiling pkg-config v0.3.32
   Compiling version_check v0.9.5
   Compiling bitflags v2.10.0
   Compiling simd-adler32 v0.3.7
   Compiling rayon-core v1.13.0
   Compiling cc v1.2.44
   Compiling rustls-pki-types v1.13.0
   Compiling memchr v2.7.6
   Compiling paste v1.0.15
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.74
   Compiling smallvec v1.15.1
   Compiling writeable v0.6.2
   Compiling litemap v0.8.1
   Compiling rustix v1.1.2
   Compiling generic-array v0.14.9
   Compiling httparse v1.10.1
   Compiling num-traits v0.2.19
   Compiling foreign-types v0.3.2
   Compiling miniz_oxide v0.8.9
   Compiling either v1.15.0
   Compiling bytemuck v1.24.0
   Compiling linux-raw-sys v0.11.0
   Compiling fnv v1.0.7
   Compiling bytes v1.10.1
   Compiling native-tls v0.2.14
   Compiling itoa v1.0.15
   Compiling base64 v0.22.1
   Compiling anyhow v1.0.100
   Compiling base64ct v1.8.0
   Compiling icu_normalizer_data v2.1.1
   Compiling icu_properties_data v2.1.1
   Compiling crossbeam-epoch v0.9.18
   Compiling matrixmultiply v0.3.10
   Compiling thiserror v1.0.69
   Compiling built v0.7.7
   Compiling pem-rfc7468 v0.7.0
   Compiling arrayvec v0.7.6
   Compiling openssl-probe v0.1.6
   Compiling byteorder v1.5.0
   Compiling crossbeam-deque v0.8.6
   Compiling syn v2.0.108
   Compiling http v1.3.1
   Compiling der v0.7.10
   Compiling flate2 v1.1.5
   Compiling nom v8.0.0
   Compiling webpki-root-certs v1.0.3
   Compiling rustls-pemfile v2.2.0
   Compiling quick-error v2.0.1
   Compiling serde_core v1.0.228
   Compiling rav1e v0.7.1
   Compiling cpufeatures v0.2.17
   Compiling rawpointer v0.2.1
   Compiling utf-8 v0.7.6
   Compiling percent-encoding v2.3.2
   Compiling simd_helpers v0.1.0
   Compiling safe_arch v0.7.4
   Compiling itertools v0.12.1
   Compiling imgref v1.12.0
   Compiling serde v1.0.228
   Compiling new_debug_unreachable v1.0.6
   Compiling getrandom v0.2.16
   Compiling socks v0.3.4
   Compiling filetime v0.2.26
   Compiling rayon v1.11.0
   Compiling rand_core v0.6.4
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling weezl v0.1.10
   Compiling openssl-sys v0.9.110
   Compiling ring v0.17.14
   Compiling noop_proc_macro v0.3.0
   Compiling digest v0.10.7
   Compiling untrusted v0.9.0
   Compiling bitstream-io v2.6.0
   Compiling utf8parse v0.2.2
   Compiling zune-core v0.4.12
   Compiling ureq-proto v0.5.2
   Compiling anstyle-parse v0.2.7
   Compiling sha2 v0.10.9
   Compiling wide v0.7.33
   Compiling num-integer v0.1.46
   Compiling num-complex v0.4.6
   Compiling zune-jpeg v0.4.21
   Compiling approx v0.5.1
   Compiling pxfm v0.1.25
   Compiling loop9 v0.1.5
   Compiling avif-serialize v0.8.6
   Compiling fdeflate v0.3.7
   Compiling zune-inflate v0.2.54
   Compiling num-bigint v0.4.6
   Compiling anstyle v1.0.13
   Compiling ab_glyph_rasterizer v0.1.10
   Compiling byteorder-lite v0.1.0
   Compiling utf8_iter v1.0.4
   Compiling xattr v1.6.1
   Compiling color_quant v1.1.0
   Compiling rustls v0.23.34
   Compiling bit_field v0.10.3
   Compiling colorchoice v1.0.4
   Compiling lebe v0.5.3
   Compiling ttf-parser v0.25.1
   Compiling tar v0.4.44
   Compiling rgb v0.8.52
   Compiling anstyle-query v1.1.4
   Compiling is_terminal_polyfill v1.70.2
   Compiling image-webp v0.2.4
   Compiling gif v0.13.3
   Compiling anstream v0.6.21
   Compiling form_urlencoded v1.2.2
   Compiling png v0.18.0
   Compiling num-iter v0.1.45
   Compiling aho-corasick v1.1.4
   Compiling qoi v0.4.1
   Compiling webpki-roots v1.0.3
   Compiling tracing-core v0.1.34
   Compiling clap_lex v0.7.6
   Compiling strsim v0.11.1
   Compiling subtle v2.6.1
   Compiling regex-syntax v0.8.8
   Compiling ttf-parser v0.15.2
   Compiling option-ext v0.2.0
   Compiling pin-project-lite v0.2.16
   Compiling heck v0.5.0
   Compiling num-rational v0.4.2
   Compiling simba v0.8.1
   Compiling tracing v0.1.41
   Compiling maybe-rayon v0.1.1
   Compiling dirs-sys v0.4.1
   Compiling clap_builder v4.5.51
   Compiling webpki-roots v0.26.11
   Compiling ndarray v0.16.1
   Compiling libloading v0.8.9
   Compiling iana-time-zone v0.1.64
   Compiling num v0.4.3
   Compiling smallvec v2.0.0-alpha.10
   Compiling chrono v0.4.42
   Compiling dirs v5.0.1
   Compiling moxcms v0.7.9
   Compiling synstructure v0.13.2
   Compiling owned_ttf_parser v0.25.1
   Compiling owned_ttf_parser v0.15.2
   Compiling regex-automata v0.4.13
   Compiling ab_glyph v0.2.32
   Compiling rusttype v0.9.3
   Compiling zerofrom-derive v0.1.6
   Compiling yoke-derive v0.8.1
   Compiling zerovec-derive v0.11.2
   Compiling displaydoc v0.2.5
   Compiling zerocopy-derive v0.8.27
   Compiling equator-macro v0.4.2
   Compiling openssl-macros v0.1.1
   Compiling thiserror-impl v1.0.69
   Compiling profiling-procmacros v1.0.17
   Compiling fax_derive v0.2.0
   Compiling num-derive v0.4.2
   Compiling arg_enum_proc_macro v0.3.4
   Compiling serde_derive v1.0.228
   Compiling profiling v1.0.17
   Compiling clap_derive v4.5.49
   Compiling fax v0.2.6
   Compiling equator v0.4.2
   Compiling rustls-webpki v0.103.8
   Compiling aligned-vec v0.6.4
   Compiling v_frame v0.3.9
   Compiling av1-grain v0.2.5
   Compiling zerofrom v0.1.6
   Compiling yoke v0.8.1
   Compiling zerovec v0.11.5
   Compiling zerotrie v0.2.3
   Compiling regex v1.12.2
   Compiling clap v4.5.51
   Compiling tinystr v0.8.2
   Compiling potential_utf v0.1.4
   Compiling icu_collections v2.1.1
   Compiling icu_locale_core v2.1.1
   Compiling icu_provider v2.1.1
   Compiling half v2.7.1
   Compiling ppv-lite86 v0.2.21
   Compiling icu_normalizer v2.1.1
   Compiling icu_properties v2.1.1
   Compiling rand_chacha v0.3.1
   Compiling exr v1.73.0
   Compiling tiff v0.10.3
   Compiling nalgebra v0.32.6
   Compiling ureq v3.1.2
   Compiling rand v0.8.5
   Compiling idna_adapter v1.2.1
   Compiling idna v1.1.0
   Compiling rand_distr v0.4.3
   Compiling url v2.5.7
   Compiling ort-sys v2.0.0-rc.10
   Compiling ureq v2.12.1
   Compiling ort v2.0.0-rc.10
   Compiling ravif v0.11.20
   Compiling image v0.25.8
   Compiling imageproc v0.25.0
   Compiling yolov8-rs v0.1.0 (/media/4tbdrive/engines/ultralytics/examples/YOLOv8-ONNXRuntime-Rust)
error[E0432]: unresolved imports `ort::CPUExecutionProvider`, `ort::CUDAExecutionProvider`, `ort::ExecutionProvider`, `ort::ExecutionProviderDispatch`, `ort::TensorRTExecutionProvider`
 --> src/ort_backend.rs:8:5
  |
8 |     CPUExecutionProvider, CUDAExecutionProvider, ExecutionProvider, ExecutionProviderDispatch,
  |     ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^ no `ExecutionProviderDispatch` in the root
  |     |                     |                      |
  |     |                     |                      no `ExecutionProvider` in the root
  |     |                     |                      help: a similar name exists in the module: `execution_providers`
  |     |                     no `CUDAExecutionProvider` in the root
  |     no `CPUExecutionProvider` in the root
9 |     TensorRTExecutionProvider,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `TensorRTExecutionProvider` in the root
  |
  = help: consider importing this struct instead:
          ort::execution_providers::CPUExecutionProvider
  = help: consider importing this struct instead:
          ort::execution_providers::CUDAExecutionProvider
  = help: consider importing this trait instead:
          ort::execution_providers::ExecutionProvider
  = help: consider importing this struct instead:
          ort::execution_providers::ExecutionProviderDispatch
  = help: consider importing this struct instead:
          ort::execution_providers::TensorRTExecutionProvider

error[E0432]: unresolved imports `ort::Session`, `ort::SessionBuilder`
  --> src/ort_backend.rs:11:11
   |
11 | use ort::{Session, SessionBuilder};
   |           ^^^^^^^  ^^^^^^^^^^^^^^ no `SessionBuilder` in the root
   |           |
   |           no `Session` in the root
   |           help: a similar name exists in the module (notice the capitalization): `session`
   |
   = help: consider importing this struct instead:
           ort::session::Session
   = help: consider importing this struct instead:
           ort::session::builder::SessionBuilder

error[E0432]: unresolved imports `ort::TensorElementType`, `ort::ValueType`
  --> src/ort_backend.rs:12:11
   |
12 | use ort::{TensorElementType, ValueType};
   |           ^^^^^^^^^^^^^^^^^  ^^^^^^^^^ no `ValueType` in the root
   |           |
   |           no `TensorElementType` in the root
   |
   = help: consider importing this enum instead:
           ort::tensor::TensorElementType
   = help: consider importing this enum instead:
           ort::value::ValueType

error[E0433]: failed to resolve: could not find `ValueType` in `ort`
  --> src/ort_backend.rs:69:25
   |
69 |             if let ort::ValueType::Tensor { ty, dimensions } = &i.input_type {
   |                         ^^^^^^^^^ could not find `ValueType` in `ort`
   |
help: consider importing this enum
   |
 3 + use ort::value::ValueType;
   |
help: if you import `ValueType`, refer to it directly
   |
69 -             if let ort::ValueType::Tensor { ty, dimensions } = &i.input_type {
69 +             if let ValueType::Tensor { ty, dimensions } = &i.input_type {
   |

error[E0433]: failed to resolve: could not find `ValueType` in `ort`
   --> src/ort_backend.rs:211:25
    |
211 |             if let ort::ValueType::Tensor { ty, dimensions } = &i.input_type {
    |                         ^^^^^^^^^ could not find `ValueType` in `ort`
    |
help: consider importing this enum
    |
  3 + use ort::value::ValueType;
    |
help: if you import `ValueType`, refer to it directly
    |
211 -             if let ort::ValueType::Tensor { ty, dimensions } = &i.input_type {
211 +             if let ValueType::Tensor { ty, dimensions } = &i.input_type {
    |

error[E0277]: the trait bound `SessionInputValue<'_>: From<ArrayBase<ViewRepr<&half::f16>, Dim<IxDynImpl>>>` is not satisfied
   --> src/ort_backend.rs:326:48
    |
326 |         let ys = self.session.run(ort::inputs![xs.view()]?)?;
    |                                   -------------^^^^^^^^^-
    |                                   |            |
    |                                   |            the trait `From<ArrayBase<ViewRepr<&half::f16>, Dim<IxDynImpl>>>` is not implemented for `SessionInputValue<'_>`
    |                                   required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              `SessionInputValue<'_>` implements `From<&ort::value::Value<T>>`
              `SessionInputValue<'_>` implements `From<ValueRef<'_, T>>`
              `SessionInputValue<'_>` implements `From<ValueRefMut<'_, T>>`
              `SessionInputValue<'_>` implements `From<ort::value::Value<T>>`
    = note: required for `ArrayBase<ViewRepr<&half::f16>, Dim<IxDynImpl>>` to implement `Into<SessionInputValue<'_>>`
help: consider removing this method call, as the receiver has type `ArrayBase<CowRepr<'_, half::f16>, Dim<IxDynImpl>>` and `ArrayBase<CowRepr<'_, half::f16>, Dim<IxDynImpl>>: From<ArrayBase<ViewRepr<&half::f16>, Dim<IxDynImpl>>>` trivially holds
    |
326 -         let ys = self.session.run(ort::inputs![xs.view()]?)?;
326 +         let ys = self.session.run(ort::inputs![xs]?)?;
    |

error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> src/ort_backend.rs:326:35
    |
326 |         let ys = self.session.run(ort::inputs![xs.view()]?)?;
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `[SessionInputValue<'_>; 1]`
    |
    = help: the trait `Try` is not implemented for `[SessionInputValue<'_>; 1]`

error[E0277]: the trait bound `SessionInputValue<'_>: From<ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>>` is not satisfied
   --> src/ort_backend.rs:364:48
    |
364 |         let ys = self.session.run(ort::inputs![xs.view()]?)?;
    |                                   -------------^^^^^^^^^-
    |                                   |            |
    |                                   |            the trait `From<ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>>` is not implemented for `SessionInputValue<'_>`
    |                                   required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              `SessionInputValue<'_>` implements `From<&ort::value::Value<T>>`
              `SessionInputValue<'_>` implements `From<ValueRef<'_, T>>`
              `SessionInputValue<'_>` implements `From<ValueRefMut<'_, T>>`
              `SessionInputValue<'_>` implements `From<ort::value::Value<T>>`
    = note: required for `ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>` to implement `Into<SessionInputValue<'_>>`
help: consider removing this method call, as the receiver has type `ArrayBase<CowRepr<'_, f32>, Dim<IxDynImpl>>` and `ArrayBase<CowRepr<'_, f32>, Dim<IxDynImpl>>: From<ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>>` trivially holds
    |
364 -         let ys = self.session.run(ort::inputs![xs.view()]?)?;
364 +         let ys = self.session.run(ort::inputs![xs]?)?;
    |

error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> src/ort_backend.rs:364:35
    |
364 |         let ys = self.session.run(ort::inputs![xs.view()]?)?;
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `[SessionInputValue<'_>; 1]`
    |
    = help: the trait `Try` is not implemented for `[SessionInputValue<'_>; 1]`

Some errors have detailed explanations: E0277, E0432, E0433.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `yolov8-rs` (lib) due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
```

### Environment

```
Ultralytics 8.3.223 🚀 Python-3.12.6 torch-2.9.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32109MiB)
Setup complete ✅ (20 CPUs, 125.5 GB RAM, 850.0/912.8 GB disk)

OS                     Linux-6.14.0-33-generic-x86_64-with-glibc2.39
Environment            Linux
Python                 3.12.6
Install                git
Path                   /home/andre/.pyenv/versions/3.12.6/envs/ultralytics/lib/python3.12/site-packages/ultralytics
RAM                    125.48 GB
Disk                   850.0/912.8 GB
CPU                    Intel Core i9-9820X 3.30GHz
CPU count              20
GPU                    NVIDIA GeForce RTX 5090, 32109MiB
GPU count              2
CUDA                   12.8

numpy                  ✅ 2.2.6>=1.23.0
matplotlib             ✅ 3.10.7>=3.3.0
opencv-python          ✅ 4.12.0.88>=4.6.0
pillow                 ✅ 12.0.0>=7.1.2
pyyaml                 ✅ 6.0.3>=5.3.1
requests               ✅ 2.32.5>=2.23.0
scipy                  ✅ 1.16.3>=1.4.1
torch                  ✅ 2.9.0>=1.8.0
torch                  ✅ 2.9.0!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision            ✅ 0.24.0>=0.9.0
psutil                 ✅ 7.1.2
polars                 ✅ 1.35.1
ultralytics-thop       ✅ 2.0.18>=2.0.18
```

### Minimal Reproducible Example

```
$ ultralytics/examples/YOLOv8-ONNXRuntime-Rust$ cargo build
```

### Additional

_No response_

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by andrenatal**
This fixes all dependencies and conflicts and outdated references, and also replaces ort's feature `load-dynamic` by `download-binaries`  in order to streamline the test and avoid conflicts and dependency hells by ensuring that ort will download the compatible onnxruntime with their libraries instead of leaving this burden to the user.

I didn't test all tasks, but with my custom segmentation model fine tuned on v12 with TRT as EP, and it worked well.

```
andre@5090:/media/4tbdrive/engines/ultralytics/examples/YOLOv8-ONNXRuntime-Rust$ cargo run --release -- --trt --model ../../ultralytics/yolo11s/weights/best.onnx  --source /mnt/seagate8tbhdd/corpora/ww/20251023_183926.jpg --plot
    Finished `release` profile [optimized] target(s) in 0.10s
     Running `target/release/yolov8-rs --trt --model ../../ultralytics/yolo11s/weights/best.onnx --source /mnt/seagate8tbhdd/corpora/ww/20251023_183926.jpg --plot`

Summary:
> Task: Segment (Ultralytics 8.3.223)
> EP: Trt(0) (May still fall back to CPU)
> Dtype: Float32
> Batch: 1 (Const), Height: 1024 (Const), Width: 1024 (Const)
> nc: 1 nk: 0, nm: 32, conf: 0.3, kconf: 0.55, iou: 0.45

[YOLOResult { Probs(top5): None, Bboxes: Some([Bbox { xmin: 306.4148, ymin: 490.0121, width: 42.646942, height: 60.136475, id: 0, confidence: 0.81982994 }, Bbox { xmin: 463.94058, ymin: 479.714, width: 37.551453, height: 60.74472, id: 0, confidence: 0.81061566 }, Bbox { xmin: 348.7171, ymin: 484.96402, width: 60.52887, height: 74.15277, id: 0, confidence: 0.8078608 }, Bbox { xmin: 408.06543, ymin: 483.1853, width: 59.818146, height: 74.84482, id: 0, confidence: 0.7914389 }, Bbox { xmin: 271.97192, ymin: 482.2528, width: 35.3869, height: 58.749054, id: 0, confidence: 0.78620553 }, Bbox { xmin: 465.2069, ymin: 533.7373, width: 36.234375, height: 42.655212, id: 0, confidence: 0.74176407 }, Bbox { xmin: 295.93365, ymin: 534.1864, width: 36.07617, height: 44.337097, id: 0, confidence: 0.7351136 }, Bbox { xmin: 500.5976, ymin: 481.83496, width: 27.625092, height: 48.804535, id: 0, confidence: 0.7129038 }, Bbox { xmin: 262.7015, ymin: 525.72656, width: 29.16925, height: 38.352783, id: 0, confidence: 0.71173936 }, Bbox { xmin: 500.91168, ymin: 529.65344, width: 24.007935, height: 27.788635, id: 0, confidence: 0.69122314 }, Bbox { xmin: 402.16302, ymin: 555.23755, width: 29.237305, height: 24.866516, id: 0, confidence: 0.68075746 }, Bbox { xmin: 334.45264, ymin: 547.5301, width: 29.54834, height: 26.823486, id: 0, confidence: 0.672197 }, Bbox { xmin: 366.01437, ymin: 556.08655, width: 32.782227, height: 20.897095, id: 0, confidence: 0.6294283 }, Bbox { xmin: 434.4512, ymin: 552.0508, width: 32.31659, height: 30.24591, id: 0, confidence: 0.6160569 }, Bbox { xmin: 253.49759, ymin: 489.37695, width: 19.601059, height: 38.250732, id: 0, confidence: 0.54045147 }, Bbox { xmin: 524.1877, ymin: 515.8112, width: 15.1328125, height: 23.167603, id: 0, confidence: 0.48857376 }, Bbox { xmin: 245.84198, ymin: 520.7802, width: 19.975983, height: 31.14624, id: 0, confidence: 0.41062564 }, Bbox { xmin: 528.6762, ymin: 496.6214, width: 15.881714, height: 20.435822, id: 0, confidence: 0.37628454 }]), Keypoints: None, Masks: Some(18) }]
```

fixes #22556

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

### 🌟 Summary
Fixes and updates the YOLOv8 ONNX Runtime Rust example to work with ORT 2.0 RC5, resolving build/runtime issues and aligning with the latest API changes.

### 📊 Key Changes
- Switch ORT feature from `load-dynamic` to `download-binaries` in Cargo.toml for easier setup
- Update ORT imports to new module paths (execution_providers, session, tensor, value)
- Adjust handling of `ValueType::Tensor` to use `shape` and `dimension_symbols` fields
- Change session run methods to take `&mut self` to match ORT’s mutable run API
- Prepare input using `ort::value::Value::from_array` and pass via `ort::inputs![input]`
- Pre-compute output shapes to avoid borrow conflicts during `session.run`
- Update tensor extraction logic to use `try_extract_tensor` returning `(shape, slice)` and reconstruct ndarrays accordingly
- Refresh output shape/dtype access to new API fields

### 🎯 Purpose & Impact
- Restores functionality of the Rust ONNX Runtime example and fixes issue #22556
- Ensures compatibility with ORT 2.0.0-rc.5 and latest API changes
- Simplifies environment setup by downloading ORT binaries automatically
- Improves stability, profiling clarity, and correctness of FP16/FP32 inference paths

### CODE REVIEW

**Comment by andrenatal** [comment]
I have read the CLA Document and I sign the CLA

**Comment by UltralyticsAssistant** [comment]
👋 Hello @andrenatal, thank you for submitting a `ultralytics/ultralytics` 🚀 PR! This is an automated review helper to streamline the process. An Ultralytics engineer will be with you shortly.

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any relevant issues (e.g. https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics Continuous Integration (CI) checks are passing. If any checks fail, please address the issues: https://docs.ultralytics.com/help/CI/
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features: https://docs.ultralytics.com/
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message: https://docs.ultralytics.com/help/CLA/
- ✅ **Minimize Changes**: Limit your changes to the minimum necessary for your bug fix or feature addition. "It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is." — Bruce Lee

For more guidance, please refer to our Contributing Guide: https://docs.ultralytics.com/help/contributing/. Don't hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

File: examples/YOLOv8-ONNXRuntime-Rust/src/ort_backend.rs [hunk 1]
```diff
@@ -321,28 +337,43 @@ impl OrtBackend {
...
                 if profile {
                     println!("[ORT D2H]: {:?}", t.elapsed());
                 }
 
                 // f16->f32
                 let t_ = std::time::Instant::now();
-                let v = v.mapv(f16::to_f32);
+                // build ndarray from the returned slice using the runtime output shape
+                let out_shape = out_shapes[idx].clone();
+                let dims = out_shape.iter().map(|&d| d as usize).collect::<Vec<_>>();
```
Comment (UltralyticsAssistant) [inline examples/YOLOv8-ONNXRuntime-Rust/src/ort_backend.rs:374]: ⚠️ **HIGH**: Casting output dimensions with `d as usize` will wrap negative values into huge `usize`s, which can happen when ORT reports dynamic dimensions like `-1`. That can explode the allocation or panic when `Array::from_shape_vec` validates the size. Please validate each dimension (e.g. handle `-1`/unknowns by inferring from `slice.len()` or by early erroring) instead of blindly casting. The same issue appears in the fp32 branch below.

**Review by UltralyticsAssistant — COMMENTED** [review]
## 🔍 PR Review

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

Please guard the new output-shape reconstruction against dynamic dimensions before merging; `-1` dims from ORT currently cast to enormous `usize`s and will crash both fp16 and fp32 inference paths.

💬 Posted 1 inline comment
